//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> NID { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
