//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public int Address { get; set; }
        public int SalePrice { get; set; }
        public int StartingPrice { get; set; }
        public int SubPropertyType { get; set; }
        public int BedRoom { get; set; }
        public int WashRoom { get; set; }
        public int DrawingRoom { get; set; }
        public int Varanda { get; set; }
        public int FlatSize { get; set; }
        public int BulidingYear { get; set; }
        public int FloorLevel { get; set; }
        public string Purpose { get; set; }
        public bool Parking { get; set; }
        public System.DateTime PublishDate { get; set; }
        public int Status { get; set; }
    }
}
