//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public string PropertyName { get; set; }
        public int Area { get; set; }
        public string Address { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public int SalePrice { get; set; }
        public int SubPropertyType { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> WashRoom { get; set; }
        public Nullable<int> Varanda { get; set; }
        public Nullable<bool> DrawingRoom { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<int> FlatSize { get; set; }
        public Nullable<int> BulidingYear { get; set; }
        public Nullable<int> FloorLevel { get; set; }
        public string Preference { get; set; }
        public System.DateTime PublishDate { get; set; }
        public int Status { get; set; }
        public string CoverUrl { get; set; }
        public Nullable<int> Purpose { get; set; }
    }
}
