//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBooking
    {
        public int BId { get; set; }
        public Nullable<int> BPropertyId { get; set; }
        public Nullable<int> BOwnerId { get; set; }
        public Nullable<System.DateTime> BTime { get; set; }
        public string BName { get; set; }
        public string BMobile { get; set; }
        public string BNID { get; set; }
        public string BGender { get; set; }
        public Nullable<System.DateTime> BDOB { get; set; }
        public string BEmail { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string PropertyName { get; set; }
        public Nullable<int> Area { get; set; }
        public string AreaName { get; set; }
        public string Address { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public Nullable<int> SubPropertyType { get; set; }
        public string SubTypeName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> WashRoom { get; set; }
        public Nullable<int> Varanda { get; set; }
        public Nullable<bool> DrawingRoom { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<int> FlatSize { get; set; }
        public Nullable<int> BulidingYear { get; set; }
        public Nullable<int> FloorLevel { get; set; }
        public string Preference { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public string CoverUrl { get; set; }
        public Nullable<int> Purpose { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerGerder { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Mobile { get; set; }
        public string NID { get; set; }
    }
}
